# Generated by Django 5.0.7 on 2024-08-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('display_data_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('otp', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pne_support_monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROACTIVE', 'PROACTIVE'), ('DAILY_SUPPORT', 'DAILY_SUPPORT'), ('PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT'), ('POST_DEPLOYMENT_SQA', 'POST_DEPLOYMENT_SQA')], max_length=100)),
                ('subject', models.TextField()),
                ('details', models.TextField()),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('NOT_ASSIGNED', 'NOT_ASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('NOT_NEEDED', 'NOT_NEEDED')], max_length=100)),
                ('created_by_name', models.CharField(max_length=255)),
                ('created_by_username', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('department', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('TECHOPS', 'TECHOPS'), ('CUSTOMER_SUPPORT', 'CUSTOMER_SUPPORT'), ('BUSINESS', 'BUSINESS'), ('UNDEFINED', 'UNDEFINED')], default='UNDEFINED', max_length=30)),
                ('admin_access', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('tk_otp_mnp_access', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('wallet_mdr_limit_access', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('tallypay_transaction_status_check', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('wallet_statement_details', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('tk_data_missing', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('service_health_check', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('eventapp_event', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('tallypay_issuer', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('tallypay_activity_log', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('sqr_timeout_cases', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('pne_log', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
