# Generated by Django 5.0.7 on 2024-08-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='sqr_data_download',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
