# Generated by Django 5.0.7 on 2024-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0004_corporate_merchant_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate_merchant_registration',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
