# Generated by Django 5.0.7 on 2024-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0005_corporate_merchant_registration_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='check_wallet_or_nid',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
