# Generated by Django 5.0.7 on 2024-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0006_user_profile_check_wallet_or_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_product_engineering_manager',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
