# Generated by Django 5.0.7 on 2024-09-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0007_user_profile_is_product_engineering_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pne_support_monitoring',
            name='action_type',
            field=models.CharField(choices=[('PROACTIVE', 'PROACTIVE'), ('DAILY_SUPPORT', 'DAILY_SUPPORT'), ('PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT'), ('POST_DEPLOYMENT_SQA', 'POST_DEPLOYMENT_SQA'), ('DEVELOPMENT', 'DEVELOPMENT')], max_length=100),
        ),
    ]
