# Generated by Django 5.0.7 on 2024-09-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0008_alter_pne_support_monitoring_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='can_check_remote_end_status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
