# Generated by Django 5.0.7 on 2024-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0009_user_profile_can_check_remote_end_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pne_support_monitoring',
            name='action_type',
            field=models.CharField(choices=[('PROACTIVE', 'PROACTIVE'), ('DAILY_SUPPORT', 'DAILY_SUPPORT'), ('PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT'), ('POST_DEPLOYMENT_SQA', 'POST_DEPLOYMENT_SQA'), ('DEVELOPMENT', 'DEVELOPMENT'), ('OPERATIONS', 'OPERATIONS'), ('CUSTOMER_CARE_SUPPORT', 'CUSTOMER_CARE_SUPPORT')], max_length=100),
        ),
    ]
