# Generated by Django 5.0.7 on 2024-09-01 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0011_taskupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
