# Generated by Django 5.0.7 on 2024-10-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0012_taskupdate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pne_support_monitoring',
            name='action_type',
            field=models.CharField(choices=[('PROACTIVE', 'PROACTIVE'), ('DAILY_SUPPORT', 'DAILY_SUPPORT'), ('PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT'), ('POST_DEPLOYMENT_SQA', 'POST_DEPLOYMENT_SQA'), ('DEVELOPMENT', 'DEVELOPMENT'), ('OPERATIONS', 'OPERATIONS'), ('CUSTOMER_CARE_SUPPORT', 'CUSTOMER_CARE_SUPPORT'), ('BUG', 'BUG')], max_length=100),
        ),
    ]
