# Generated by Django 5.1.4 on 2024-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0013_alter_pne_support_monitoring_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pne_support_monitoring',
            name='action_type',
            field=models.CharField(choices=[('PROACTIVE', 'PROACTIVE'), ('DAILY_SUPPORT', 'DAILY_SUPPORT'), ('PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT'), ('POST_DEPLOYMENT_SQA', 'POST_DEPLOYMENT_SQA'), ('DEVELOPMENT', 'DEVELOPMENT'), ('OPERATIONS', 'OPERATIONS'), ('CUSTOMER_CARE_SUPPORT', 'CUSTOMER_CARE_SUPPORT'), ('BUG', 'BUG'), ('EMAIL', 'EMAIL')], max_length=100),
        ),
    ]
