# Generated by Django 5.1.6 on 2025-05-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0014_alter_pne_support_monitoring_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('min_amount_per_txn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount_per_txn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_count_per_day', models.IntegerField(blank=True, null=True)),
                ('max_amount_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_count_per_month', models.IntegerField(blank=True, null=True)),
                ('max_amount_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='customer_care_portal',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
