# Generated by Django 5.1.6 on 2025-05-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0015_wallettransactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='debit_credit_block_unblock',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
