# Generated by Django 5.1.6 on 2025-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0016_user_profile_debit_credit_block_unblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('permission', models.BooleanField(default=False)),
                ('chatagory', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'transaction_permission',
            },
        ),
    ]
