# Generated by Django 5.1.6 on 2025-05-29 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0017_transactionpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpermission',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactionpermission',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
