# Generated by Django 5.1.6 on 2025-05-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0018_transactionpermission_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpermission',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
