# Generated by Django 5.1.6 on 2025-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0019_transactionpermission_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='complience',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
