# Generated by Django 5.1.6 on 2025-06-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0021_user_profile_complience_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpermission',
            name='executor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
