# Generated by Django 5.1.6 on 2025-06-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0022_transactionpermission_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpermission',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
