# Generated by Django 5.1.6 on 2025-06-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0023_transactionpermission_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='active',
            new_name='is_active',
        ),
    ]
