# Generated by Django 5.1.6 on 2025-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0024_rename_active_transactionpermission_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpermission',
            name='permission',
            field=models.CharField(max_length=100),
        ),
    ]
