# Generated by Django 5.1.6 on 2025-06-01 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0025_alter_transactionpermission_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='full_name',
            new_name='initiator',
        ),
        migrations.AddField(
            model_name='transactionpermission',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
