# Generated by Django 5.1.6 on 2025-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0026_rename_full_name_transactionpermission_initiator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='executor',
            new_name='executor_fullname',
        ),
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='initiator',
            new_name='executor_username',
        ),
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='user_name',
            new_name='initiator_fullname',
        ),
        migrations.AddField(
            model_name='transactionpermission',
            name='initiator_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
