# Generated by Django 5.1.6 on 2025-06-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0027_rename_executor_transactionpermission_executor_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='executor_fullname',
            new_name='executor_fullnam',
        ),
    ]
