# Generated by Django 5.1.6 on 2025-06-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0028_rename_executor_fullname_transactionpermission_executor_fullnam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpermission',
            old_name='executor_fullnam',
            new_name='executor_fullname',
        ),
    ]
