# Generated by Django 5.1.6 on 2025-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0029_rename_executor_fullnam_transactionpermission_executor_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpermission',
            name='ticket_number',
            field=models.CharField(default='TICKET-0001', max_length=100),
        ),
    ]
