# Generated by Django 5.1.6 on 2025-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0030_transactionpermission_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='complience_maker',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
