# Generated by Django 5.1.6 on 2025-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0031_user_profile_complience_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='complience_call',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
    ]
